
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bird-webui-hpa
  namespace: bird
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bird-release-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
status:
  observedGeneration: 1
  #lastScaleTime: 05:00
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
       name: memory
       current:
         averageUtilization: 70
         averageValue: 10