apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bird-release-pvc
  namespace: bird
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi