apiVersion: v1
kind: Service
metadata:
  name: bird-service
  namespace: bird
spec:
  selector:
    app: bird
  ports:
  - name: bird-service-port
    protocol: TCP
    port: 4201
    targetPort: bird-web