name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Step 1: Log in to Amazon ECR
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME  
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891376975226.dkr.ecr.us-east-1.amazonaws.com

    # Step 2: Build the Docker image
    - name: Build the Docker image
      run: |
        IMAGE_NAME=$(basename "$PWD")
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest

    # Step 3: Tag the image with ECR repository URL
    - name: Tag the Docker image
      run: |
        IMAGE_NAME=$(basename "$PWD")
        ECR_URI=891376975226.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME
        docker tag $IMAGE_NAME:latest $ECR_URI:latest

    # Step 4: Push the Docker image to ECR
    - name: Push the Docker image to ECR
      run: |
        IMAGE_NAME=$(basename "$PWD")
        ECR_URI=891376975226.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME
        docker push $ECR_URI:latest

    - name: Push the Docker image to ECR
      run: |
        IMAGE_NAME=$(basename "$PWD")
        ECR_URI=891376975226.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME
        docker push $ECR_URI:latest