name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
    - name: Testing workflow
      uses: actions/checkout@v4

    - name: Maven test
      run: mvn test
    
    - name: Checkstyle
      run: mvn checkstyle:checkstyle
     
   